package net.banatech.app.android.sabi_alarm.actions.alarm

object AlarmActions {
    const val ALARM_CREATE = "alarm-create"
    const val ALARM_DESTROY = "alarm-destroy"
    const val ALARM_UNDO_DESTROY = "alarm-undo-destroy"
    const val ALARM_EDIT = "alarm-edit"
    const val ALARM_ENABLE_SWITCH = "alarm-enable-switch"
    const val ALARM_IS_SHOW_DETAIL_SWITCH = "alarm-is-show-detail-switch"
    const val ALARM_IS_VIBRATION_SWITCH = "alarm-is-vibration-switch"
    const val ALARM_IS_REPEATABLE_SWITCH = "alarm-is-repeatable-switch"
    const val ALARM_DAY_SWITCH = "alarm-day-switch"
    const val ALARM_SOUND_SELECT = "alarm-sound-select"
    const val ALARM_SOUND_START_TIME_CHANGE = "alarm-sound-start-time-change"

    const val KEY_ID = "key-id"
    const val KEY_HOUR = "key-hour"
    const val KEY_MINUTE = "key-minute"
    const val KEY_ENABLE = "key-enable"
    const val KEY_IS_SHOW_DETAIL_SWITCH = "key-is-show-detail"
    const val KEY_IS_VIBRATION = "key-is-vibration"
    const val KEY_IS_REPEATABLE = "key-is-repeatable"
    const val KEY_DAY_ENABLE = "key-day-enable"
    const val KEY_DAY_OF_WEEK = "key-week-day-of-week"
    const val KEY_SOUND_FILE_NAME = "key-sound-file-name"
    const val KEY_CONTEXT = "key-context"
    const val KEY_SOUND_START_TIME = "key-sound-start-time"
    const val KEY_SOUND_START_TIME_TEXT = "key-sound-start-time-text"
    const val KEY_IS_DEFAULT_SOUND = "key-is-default-sound"
    const val KEY_SOUND_FILE_URI = "key-sound-file-uri"
}
